app: appDemo
stage: dev

component: websocket@dev
name: websocketDemo

inputs:
  region: ap-guangzhou
  functionName: websocket-function
  src:
    src: ./
    exclude:
      - .env
  faas:
    timeout: 10
  apigw:
    serviceTimeout: 30
    environment: release
    protocols:
      - https
