app: appDemo
stage: dev

component: websocket
name: websocketDemo

inputs:
  region: ap-guangzhou
  src:
    src: ./
    exclude:
      - .env
  faas:
    name: websocket-function
    timeout: 10
    environment:
      - envKey: TEST
        envVal: 123
    tags:
      - tagKey: TEST
        tagVal: 123
  apigw:
    timeout: 30
    environment: release
    protocols:
      - https
